<?php

namespace apiBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{


    public function findByidpr($idpr){
       $q=$this->getEntityManager()
           ->createQuery("select * from apiBundle:Produit  WHERE idpr=:idpr")
           ->setParameter(":idpr",$idpr);
       return $q->getResult();
    }

    public function findByiduser($iduser){
        $q=$this->getEntityManager()
            ->createQuery("select * from apiBundle:Produit  WHERE iduser=:iduser")
            ->setParameter(":iduser",$iduser);
        return $q->getResult();
     }
 

   

}